name: Build Runner

on:
  workflow_call:
    inputs:
      onnxruntime-version:
        type: string
        required: true
      target:
        type: string
        required: true
      args:
        type: string
        required: true
      static:
        type: boolean
        default: true
      feature-set:
        type: string
        required: true
      cuda-version:
        type: string
        required: false
        default: ""
      runs-on:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      onnxruntime-version:
        description: "ONNX Runtime version (e.g. 1.18.0)"
        type: string
        required: true
      target:
        description: "Target architecture (e.g. x86_64-unknown-linux-gnu)"
        type: string
        required: true
      args:
        description: "Arguments for the build (e.g. -t --xnnpack -N)"
        type: string
        required: true
      static:
        description: "Build static library"
        type: boolean
        default: true
      feature-set:
        description: "Feature set (e.g. train)"
        type: string
        required: true
      cuda-version:
        description: "CUDA version (e.g. 12.8.1)"
        type: string
        required: false
        default: ""
      runs-on:
        description: "Runner OS (e.g. ubuntu-24.04)"
        type: string
        required: true

env:
  XCODE_VERSION: "14.3.1"
  MACOSX_DEPLOYMENT_TARGET: "13.4"
  IPHONEOS_DEPLOYMENT_TARGET: "15.1"
  ANDROID_API: "24"

jobs:
  build:
    name: Build ${{ inputs.target }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Install cross-compile tools
        if: inputs.target == 'aarch64-unknown-linux-gnu' || inputs.target == 'aarch64-linux-android'
        run: |
          sudo apt update && sudo apt install -y gcc make gcc-14-aarch64-linux-gnu g++-14-aarch64-linux-gnu binutils-aarch64-linux-gnu
      - name: Remove unnecessary software
        if: runner.os == 'Linux'
        run: |
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
      - name: Remove unnecessary software (non-Android)
        if: runner.os == 'Linux' && inputs.target != 'aarch64-linux-android'
        run: |
          sudo rm -rf /usr/local/lib/android
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v6
      - uses: Jimver/cuda-toolkit@v0.2.30
        if: inputs.cuda-version && runner.os != 'macOS'
        with:
          cuda: ${{ inputs.cuda-version }}
          method: network
          use-github-cache: false
          # sub-packages: '["nvcc", "cudart", "cublas", "nvrtc"]'
      - uses: actions/setup-java@v4
        if: inputs.target == 'aarch64-linux-android'
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        if: inputs.target == 'aarch64-linux-android'
        with:
          add-to-path: false
          ndk-version: r28
      - name: Pin cmake version
        if: contains(inputs.target, 'apple')
        run: |
          brew uninstall cmake
          # Copied from https://github.com/actions/runner-images/pull/12791
          # Pin cmake to 3.31.6 due to a backward compatibility issue
          # https://github.com/actions/runner-images/issues/11926
          cmake_commit="b4e46db74e74a8c1650b38b1da222284ce1ec5ce"
          tap_name="local/pinned"

          echo "Creating local tap (no git)..."
          brew tap-new --no-git "$tap_name" >/dev/null

          cmake_formula_dir="$(brew --repo "$tap_name")/Formula"
          mkdir -p "$cmake_formula_dir"

          cmake_rb_link="https://raw.githubusercontent.com/Homebrew/homebrew-core/$cmake_commit/Formula/c/cmake.rb"
          cmake_rb_path="$cmake_formula_dir/cmake.rb"

          echo "Downloading cmake.rb from $cmake_rb_link"
          curl -fsSL "$cmake_rb_link" -o "$cmake_rb_path"

          echo "Installing cmake 3.31.6 from custom tap..."
          brew install "$tap_name/cmake"
        shell: bash
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run builder
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: deno run -A src/build.ts -v ${{ inputs.onnxruntime-version }} ${{ inputs.static && '-s' || '' }} ${{ inputs.args }}
      - name: Attest build
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: artifact.tar.lzma2
          subject-name: ${{ inputs.target }}${{ inputs.feature-set != 'none' && format('+{0}', inputs.feature-set) || '' }}.tar.lzma2
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.target }}${{ inputs.feature-set != 'none' && format('+{0}', inputs.feature-set) || '' }}.tar.lzma2
          path: artifact.tar.lzma2
          if-no-files-found: error
